version: '3.5'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: adserver
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - '13306:3306'
    command: 'mysqld'
  redis:
    image: 'redis:6.0'
    ports:
      - '16379:6379'
    volumes:
      - './redis/data:/data'
